# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2def7d8d03635432e1e15b3c9d9a089b437456e1630d33c121073ecd41fcb6e2851f3684754dd311b9e2037301248105f00242ed8c7df6081fc4c53462968dfa

test:
  secret_key_base: 2dc1ecd8f62f6557bf69777e2b220b41314cfdbfc5f2bf082aee38213a74e34a28251ec36ac912fc6b2c20879f43d3e35d1e1d317f6e91099b0a5be69dc52c01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
